name: json syntax check

on:
  push:
    paths:
      - "**.json"
  pull_request:

jobs:
  json-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2

      - name: json syntax check
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v1.4.0
